<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\fonts\Fredoka.ttf" />
    <None Remove="assets\img\back.png" />
    <None Remove="assets\img\background.png" />
    <None Remove="assets\img\background_aquarium.png" />
    <None Remove="assets\img\background_arena.png" />
    <None Remove="assets\img\background_bank.png" />
    <None Remove="assets\img\background_cage.png" />
    <None Remove="assets\img\background_mainmenu.png" />
    <None Remove="assets\img\background_reg.png" />
    <None Remove="assets\img\background_terrarium.png" />
    <None Remove="assets\img\close.png" />
    <None Remove="assets\img\icon_food.png" />
    <None Remove="assets\img\icon_money.png" />
    <None Remove="assets\img\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\fonts\Fredoka.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\back.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background_aquarium.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background_arena.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background_bank.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background_cage.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background_mainmenu.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background_reg.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\background_terrarium.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\close.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\icon_food.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\icon_money.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="assets\img\logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
